### ISSUE TITLE
ReCaptcha

### ISSUE THREAD

**Issue by piotrslabik1** [piotr-cz/mod_freshmail2#2]
Wygląda na to, że wszystko działa. Dzięki wielkie. Tego szukałem.
Proponuję dodać element wymieniony w temacie.

Bug1:Po zainstalowaniu modułu w Joomla podany w nim link do dokumentacji jest błędny.
Bug2: Na stronie Freshmaila widnieje informacja, ze moduł ten jest sprzed 2 lat co odstrasza.

Pozdrawiam,
Piotr

**Comment by piotr-cz** [comment]
Przepraszam, przypadkowo zamknąłem, dzięki za zgłoszenie.

ad 1) poprawione (na razie jeszcze nie ma w releasie)
ad 2) skontaktuję się z ekipą FreshMail

ad CAPTCHA: funkcjonalność można przetestować pobierając achiwum z gałęzi [feature-captcha](https://github.com/piotr-cz/mod_freshmail2/tree/feature-captcha): https://github.com/piotr-cz/mod_freshmail2/archive/feature-captcha.zip.

Mogę cię prosić o przetestowanie?

Instrukcja do włączenia pluginu dystrybuowanego z Joomla!: [How do you use Recaptcha in Joomla?
](https://docs.joomla.org/How_do_you_use_Recaptcha_in_Joomla%3F)

Przy okazji: miałeś problemy ze spamem?

**Comment by piotr-cz** [comment]
ping @piotrslabik1 możesz przetestować?

**Comment by piotr-cz** [comment]
Przygotuję nową wersję modułu z zaimplemetowaną _Captcha_ kiedy ten powiązany [bug](https://github.com/joomla/joomla-cms/pull/10601) zostanie włączony do oficjalnego wydania Joomla!.

**Comment by piotr-cz** [comment]
Integracja z Captcha wprowadzona w [v1.2.0](https://github.com/piotr-cz/mod_freshmail2/releases/tag/v1.2.0)
